source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

# ignore warnings from pods... because a clean environment is a happy environment
inhibit_all_warnings!

# production 
def production_pods
    inherit! :search_paths
    
    # Networking
    pod 'Alamofire'
    pod 'AlamofireObjectMapper'
    pod 'ReachabilitySwift'
    
    # S3
    pod 'AWSS3'

    # Camera
    pod 'SCRecorder', :git => 'https://github.com/mcgraw/SCRecorder'
    
    # Core
    pod 'RealmSwift'
    pod 'PromiseKit'
    pod 'R.swift'
    pod 'Signals', '~> 5.0'
    pod 'Locksmith'
    pod 'Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Performance'
    pod 'Adjust'
    
    pod 'lottie-ios'
     
    pod 'Branch'
    pod 'Leanplum-iOS-SDK'
    
    # Sharing
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'TwitterKit'
    
    # Caching
    pod 'Kingfisher'

    # Interface
    pod 'PureLayout'
    pod 'Toast-Swift'
    pod 'SwiftMessages'
    pod 'ICGVideoTrimmer'
    pod 'CTKFlagPhoneNumber'
    
    pod 'ActiveLabel', :git => 'https://github.com/BeMaverickCo/ActiveLabel.swift'
    # Logging
    pod 'XCGLogger'

    # Reporting
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'NewRelicAgent'
    
end

target 'Production' do
    
    production_pods
end

target 'Development' do
    production_pods
   
end



post_install do |installer|

    installer.pods_project.targets.each do |target|

        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0.0'
        end

    end

end
