<script>
(function(w, d, u) {
    w.readyQ = [];
    w.bindReadyQ = [];
    function p(x, y) {
        if (x == "ready") {
            w.bindReadyQ.push(y);
        } else {
            w.readyQ.push(x);
        }
    }
    var a = { ready: p, bind: p };
    w.$ = w.jQuery = function(f) {
        if (f === d || f === u) {
            return a;
        } else {
            p(f);
        }
    };
})(window, document);
window._cachedMessages = [];
var messageListener = function(e) {
    if (_cachedMessages) {
        _cachedMessages.push(e);
    }
};
if (window.addEventListener) {
    addEventListener("message", messageListener, false);
} else {
    attachEvent("onmessage", messageListener);
}
</script>
