<style>
.type .global-bd {
    opacity: 0;
}
.no-opacity .type-not-inited .global-bd {
    visibility: hidden;
}
.menu {
    display: none;
    opacity: 0;
}
.global-nav-overlay {
    display: none;
}
#event-strip .content {
    opacity: 0;
}
.no-mobile #event-strip .content {
    height: 54px;
}
.registration-tooltip {
    display: none;
}
.global-video-proxy-container .proxy-wrap {
    position: absolute !important;
    z-index: 101;
}
.site-inited #popup-mask, .site-inited #popup {
    -webkit-transition: all 0.25s ease;
    transition: all 0.25s ease;
}
.smartbanner {
    display: none;
}
iframe[name="google_conversion_frame"] {
    position: absolute;
}
.hide-live-strip .live-strip {
    display: none;
}
.no-header .global-hd {
    display:none;
}
</style>
