<?php
$pageTracking = $this->pageConfig->getPageTracking();
$systemConfig = $this->systemConfig;
if ( ! isset( $pageTracking['googleAnalytics'] ) ) {
    return;
}
?>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    var slyPageViewUrl = document.location.pathname;
    if (window.slyReplacePageViewUrl) {
      slyPageViewUrl = window.slyReplacePageViewUrl; 
    }
    <?php
    $count = 0;
    foreach( $pageTracking['googleAnalytics']['ua'] as $ua ) {
    
        $count++;
        
        //print "ga('create', '$ua', '".$systemConfig->getHttpHost()."');\n";
        
        if ( $count == 1 ) {
            print "ga('create', '$ua' );\n";
            print "ga('send', 'pageview', slyPageViewUrl);\n";
        }
        else {
            print "ga('create', '$ua', 'auto', {'name': 'newTracker$count'} );\n";
            print "ga('newTracker$count.send', 'pageview', slyPageViewUrl);\n";
        }
    }
    ?>
</script>
