<?php
$metaTags = $this->metaTags();

$data = $metaTags->getData();
$additionalTags = $metaTags->getAdditionalTags();

print <<<HTML
<meta property="og:title" content="{$data['title']}"/>
<meta property="og:description" content="{$data['description']}"/>
<meta property="og:type" content="{$data['type']}"/>
<meta property="og:site_name" content="{$data['siteName']}"/>
<meta property="og:url" content="{$data['url']}"/>

<meta property="fb:admins" content="{$data['facebookAppAdmins']}"/>
<meta property="fb:app_id" content="{$data['facebookAppId']}"/>

<meta name="description" content="{$data['description']}" />
<meta name="keywords" content="{$data['keywords']}" />

{$additionalTags}
HTML;

?>
