<div class="mod generic" id="notfound">
    <div class="content">
        <div class="hd">
            <h4>Page Not Found</h4>
        </div>
        <div class="bd">
            <p>The requested page was not found</p>
            <?php
                if ( $this->requestedPage ) {
                    print '<p>'.$this->requestedPage.'</p>';
                }
            ?>
            <p><a href="/">Go Home</a></p>
        </div>
    </div>
</div>
