<?php
/**
 * To use this template <template> must be set to template_api.phtml in the
 * page config. Only the <primary> includes will be used. The includes should
 * set items into the apiData variable
 *
 */

$pageConfig = $this->pageConfig;
$format = $this->format;

// initialize the data to be empty
$this->apiData = array();

$content = '';

if ( $pageConfig->hasPrimaryFiles() ) {
    foreach( $pageConfig->getPrimaryFiles() as $file ) {
        $content .= $this->render( $file );
    }
}

if ( $format == 'xml' ) {
    header( 'Content-Type: application/xml' );
    //print $this->formatApiData()->toXml( $this->apiData );
    print $content;
}
else if ( $format == 'php' ) {
    header( 'Content-Type: text/plain' );
    print $this->formatApiData()->toPhp( $this->apiData );
}
else if ( $format == 'json' ) {

    $jsonData = $this->formatApiData()->toJson( $this->apiData );

    if ( $this->input && $this->input->callback ) {
        header( 'Content-Type: application/x-javascript' );
        
        if ( $this->input->returnHTML == '1' ) {
            print '<html><body><script>';
            print $this->input->callback.'('.$jsonData.')';
            print '</script></body></html>';
        }
        else {
            print $this->input->callback.'('.$jsonData.')';
        }
    }
    else {
        header( 'Content-Type: application/json' );
        print $jsonData;
    }
}
else {
    error_log( "unknown format: $format" );
    print $content;
}

?>
