<?php
$input = $this->input;
$site = $this->site;
$formatFormBootstrap = $this->formatFormBootstrap2();

$badgeStatus = $input->contentStatus ? $input->contentStatus : null;
$query = $input->getUnescaped( 'query' );
$count = $input->count ? $input->count : 20;
$offset = $input->offset ? $input->offset : 1;
$sort = $input->sort ? $input->sort : 'id';
$sortOrder = $input->sortOrder ? $input->sortOrder : 'desc';

$filterStatus = !is_null($badgeStatus) ? $badgeStatus : 'active';
$filterBy = array(
    'status' => $filterStatus,
    'query' => $query,
);

$sortBy = array(
    'sort' => $sort,
    'sortOrder' => $sortOrder,
);

$badges = $site->getBadges( $filterStatus, $sortBy, $count, $offset-1 );
$badgeCount = count($badges); // $site->getBadgesCount( $filterStatus );

// set the table data
$columns = array(
    // 'upDown',
    'badgeId',
    'badgeName',
    'badgePrimaryImage',
    'badgeSecondaryImage',
    'badgeColor',
    'badgeStatus',
);

$columnInfo = $this->getTableInfo()->getColumnInfo( $columns );

// we want the next click to be reverse sort order
$sortParams = array(
    'badgeStatus' => $badgeStatus,
    'query' => $query,
    'sort' => '_sort_',
    'sortOrder' => $sortOrder == 'desc' ? 'asc' : 'desc',
);

$tableInitVars = array(
    'columns' => $columns,
    'columnInfo' => $columnInfo,
    'rowIdPrefix' => 'badge',
    'dontUseGroups' => true,
    'sort' => array(
        'url' => $this->url( 'badges', $sortParams ),
        'column' => 'badge',
        'value' => $sort,
        'isDynamic' => true,
    ),
    'tableAttributes' => array( 'class' => 'table table-striped table-bordered' ),
);

$tableDataInput = array();

$tableData = $this->getTableData( $badges, $columns, $tableDataInput );

$tableInitVars['rows'] = array_keys( $tableData );

$table = $this->table( $tableData, $tableInitVars );

// pagination params
$paginationParams = array(
    'status' => $badgeStatus,
    'query' => $query,
    'sort' => $sort,
    'sortOrder' => $sortOrder,
);

$paginationVars = array(
    'offset' => $offset,
    'urlIndex' => 'badges',
    'totalItems' => $badgeCount,
    'perPage' => $count,
    'itemType' => 'Badges',
    'displayPrefix' => 'Displaying',
    'of' => 'of',
    'paginationParams' => $paginationParams,
    'hideIfEmpty' => true,
    'alwaysShowPrevNext' => true,
    'labels' => array( '&laquo; Prev', 'Next &raquo;'),
    'showItemCounts' => true,
    'showPaginationIfOnePage' => false,
    'listAttributes' => array(
       'class' => 'pagination'
    ),
    'containerAttributes' => array(
        'class' => 'pagination-wrap'
    )
);

$formItems = array();
$formItems[] = $formatFormBootstrap->getContentStatus( $badgeStatus, null );
// $formItems[] = $formatFormBootstrap->getQuery( $query, null );
$formItems[] = $formatFormBootstrap->getButton( array( 'text' => 'Filter', 'style' => 'default' ) );
?>


<div class="page-header">
    <h1 class="page-header-title">Badges</h1>
    <div class="actions-wrap">
        <!-- <a href='<?php print $this->url( 'badgeAdd' ); ?>' class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add New Badge
        </a> -->
    </div>
</div>

<?php /** Filter Form */ ?>
<div class="button-bars">
    <div class="button-bar--filter button-bar">
        <form method="get" action="<?php print $this->url( 'badges' ); ?>">
            <div class="filter">
                <?php print $formatFormBootstrap->getList( $formItems ); ?>
            </div>
        </form>
    </div>
</div>

<form method="post" action="<?php print $this->url( 'badgesEditConfirm' ); ?>" >

    <div class="table-responsive table-draggable">
        <?php print $table; ?>
    </div>

    <?php
    $formItems = array();
    $formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => 'Save Order', 'style' => 'btn btn-success' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );
    print $formatFormBootstrap->getList( $formItems );
    ?>
</form>

<div class="pagination-bar">
    <?php print $this->searchPagination( $paginationVars ); ?>
</div>
