<?php
$input = $this->input;
$site = $this->site;
$formatFormBootstrap = $this->formatFormBootstrap2();

$responseType = $input->responseType;
$challengeId = $input->challengeId;
$mentorId = $input->mentorId;
$username = $input->username;
$count = $input->count ? $input->count : 20;
$offset = $input->offset ? $input->offset : 1;
$sort = $input->sort ? $input->sort : 'createdTimestamp';
$sortOrder = $input->sortOrder ? $input->sortOrder : 'desc';

$userId = null;
if ( $username ) {
    $user = $site->getUserByUsername( $input->username );

    $userId = $user ? $user->getId() : -1;
}

$filterBy = array(
    'responseStatus' => 'active',
    'responseType' => $responseType,
    'challengeId' => $challengeId,
    'challengeUserId' => $mentorId,
    'userId' => $userId,
);

$sortBy = array(
    'sort' => $sort,
    'sortOrder' => $sortOrder,
);

$responses = $site->getResponses( $filterBy, $sortBy, $count, $offset-1 );
$responseCount = $site->getResponseCount( $filterBy );

// set the table data
$columns = array( 'responseId', 'responseStatus', 'responseType', 'responseVideoPlayer', 'responseUsername', 'responseChallengeTitle', 'responseCreatedTimestamp', 'responseEditFavorite' );

$columnInfo = $this->getTableInfo()->getColumnInfo( $columns );

// we want the next click to be reverse sort order
$sortParams = array(
    'challengeId' => $challengeId,
    'challengeUserId' => $mentorId,
    'username' => $username,
    'sort' => '_sort_',
    'sortOrder' => $sortOrder == 'desc' ? 'asc' : 'desc',
);

$tableInitVars = array(
    'columns' => $columns,
    'columnInfo' => $columnInfo,
    'rowIdPrefix' => 'response',
    'dontUseGroups' => true,
    'sort' => array(
        'url' => $this->url( 'favoriteResponsesEdit', $sortParams ),
        'column' => 'response',
        'value' => $sort,
        'isDynamic' => true,
    ),
    'tableAttributes' => array( 'class' => 'table table-striped table-bordered' ),
);

$tableDataInput = array();

$tableData = $this->getTableData( $responses, $columns, $tableDataInput );

$tableInitVars['rows'] = array_keys( $tableData );

$table = $this->table( $tableData, $tableInitVars );

// pagination params
$paginationParams = array(
    'responseType' => $responseType,
    'challengeId' => $challengeId,
    'challengeUserId' => $mentorId,
    'username' => $username,
    'sort' => $sort,
    'sortOrder' => $sortOrder,
);

$paginationVars = array(
    'offset' => $offset,
    'urlIndex' => 'favoriteResponsesEdit',
    'totalItems' => $responseCount,
    'perPage' => $count,
    'itemType' => 'Responses',
    'displayPrefix' => 'Displaying',
    'of' => 'of',
    'paginationParams' => $paginationParams,
    'hideIfEmpty' => true,
    'alwaysShowPrevNext' => true,
    'labels' => array( '&laquo; Prev', 'Next &raquo;'),
    'showItemCounts' => true,
    'showPaginationIfOnePage' => false,
    'listAttributes' => array(
       'class' => 'pagination'
    ),
    'containerAttributes' => array(
        'class' => 'pagination-wrap'
    )
);

$formItems = array();
$formItems[] = $formatFormBootstrap->getResponseType( $responseType, null );
$formItems[] = $formatFormBootstrap->getChallengeAutocomplete( $challengeId, null );
$formItems[] = $formatFormBootstrap->getMentor( $mentorId, null );

$inputSettings = array(
    'isRequired' => false
);

$optionSettings = array(
    'attributes' => array(
        'class' => 'form-item--large',
    ),
);

$formItems[] = $formatFormBootstrap->getUsername( $username, null, $inputSettings, null, $optionSettings );

$formItems[] = $formatFormBootstrap->getButton( array( 'text' => 'Filter', 'style' => 'default' ) );
?>

<h1 class="page-header">Edit Favorite Responses</h1>

<div class="button-bars">
    <div class="button-bar--filter button-bar">
        <form method="get" action="<?php print $this->url( 'favoriteResponsesEdit' ); ?>">
            <div class="filter">
                <?php print $formatFormBootstrap->getList( $formItems ); ?>
            </div>
        </form>
    </div>
</div>

<form method="post" action="<?php print $this->url( 'favoriteResponsesEditConfirm' ); ?>">
    <div class="table-responsive">
        <?php print $table; ?>
    </div>

    <div class="pagination-bar">
        <?php print $this->searchPagination( $paginationVars ); ?>
    </div>

    <div class="bd">
        <?php
        $hiddenFields = '';
        foreach ( $responses as $response ) {
            $hiddenFields .= $formatFormBootstrap->getHiddenSimple( 'responseIds[]', $response->getId() );
        }
        $formItems = array();
        $formItems[] = $formatFormBootstrap->getButton( array( 'text' => 'Submit', 'style' => 'btn btn-primary' ) );
        print $formatFormBootstrap->getList( $formItems );
        print $hiddenFields;
        ?>
    </div>
</form>

