<?php
require_once( BEMAVERICK_COMMON_ROOT_DIR . '/lib/Stream.php' );
$input = $this->input;
$site = $this->site;

// Input Fields
$featuredType = $input->featuredType ? $input->featuredType : 'maverick-stream';
$streamId = $input->streamId ? $input->streamId : null;
$stream = isset( $streamId ) ? $site->getStream( $streamId ) : null;
$sortLogic = $input->sortLogic ? $input->sortLogic : 'custom';

$formatFormBootstrap = $this->formatFormBootstrap2();

$featuredResponses = $site->getFeaturedResponses( $featuredType );
// die("<pre>featuredResponses ".print_r(array_map( function($e) { return $e->getId(); }, $featuredResponses), true)."</pre>");

$hiddenFields = array(
    $formatFormBootstrap->getHiddenSimple( 'featuredType', $featuredType ),
    $formatFormBootstrap->getHiddenSimple( 'streamId', $streamId ),
);

// set the table data
$columns = array( 'responseIdWithHiddenInput', 'responseStatus', 'responseVideoThumbnail', 'responseUsername', 'responseChallengeTitle', 'responseCreatedTimestamp', 'tableRowDelete' );

$columnInfo = $this->getTableInfo()->getColumnInfo( $columns );

$tableInitVars = array(
    'columns' => $columns,
    'columnInfo' => $columnInfo,
    'rowIdPrefix' => 'response',
    'dontUseGroups' => true,
    'tableAttributes' => array( 'class' => 'table table-striped table-bordered' ),
);

$tableDataInput = array();

$allowDuplicates = true;
$tableData = $this->getTableData( $featuredResponses, $columns, $tableDataInput, $allowDuplicates );
// die("<pre>tableData ".print_r($tableData, true)."</pre>");


$tableInitVars['rows'] = array_keys( $tableData );

$table = $this->table( $tableData, $tableInitVars );

// Stream Settings Forms
$streamSettingsForm = isset( $stream ) ? $formatFormBootstrap->getStreamSettingsForm( $stream ) : false;
$streamRotationForm = isset( $stream ) ? $formatFormBootstrap->getStreamRotationForm( $stream ) : false;
$streamTableStyles =  isset( $stream ) ? $formatFormBootstrap->getStreamTableStyles( $stream ) : false;

?>

<h1 class="page-header">Edit Response Stream</h1>

<?php if (!$streamId) : ?>
    <div class="button-bars">
        <div class="button-bar--filter button-bar">
            <form method="get" action="<?php print $this->url( 'featuredResponsesEdit' ) ?>">
                <div class="filter">
                    <?php
                    $formItems = array();
                    $formItems[] = $formatFormBootstrap->getFeaturedType( $featuredType, null, 'response', $streamId );
                    print $formatFormBootstrap->getList( $formItems );
                    ?>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>

<form method="get" action="<?php print $this->url( 'featuredResponsesEditConfirm' ); ?>" >
    <div style='display: block; float: right;'>
        <?php
        $formItems = array();
        $formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => '<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp; Save Stream', 'style' => 'btn btn-success' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );
        print $formatFormBootstrap->getList( $formItems );
        ?>
    </div>

    <?php /** Hidden Fields */ ?>
    <?php foreach($hiddenFields as $hiddenField) { print $hiddenField; } ?>


    <?php /** Stream Forms */ ?>
    <?php print $streamSettingsForm; ?>
    <?php print $streamRotationForm; ?>
    <?php print $streamTableStyles; ?>
    
    <?php /** Manage Responses */ ?>
    <div class="bd">
        <h3>Responses</h3>
        <p>Search for Responses to add and remove from the stream</p>
        <div class="filter">
            <?php
            $formItems = array();
            $formItems[] = $formatFormBootstrap->getResponseAutocomplete( null, null, 'medium', "insert", "Search by Challenge Title, Username, or Response ID" );
            print $formatFormBootstrap->getList( $formItems );
            ?>
        </div>

        <?php /** Responses Table */ ?>
        <div class="table-responsive table-draggable table-display-limit">
            <?php print $table; ?>
        </div>

        <?php
        $formItems = array();
        $formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => '<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp; Save Stream', 'style' => 'btn btn-success' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );
        print $formatFormBootstrap->getList( $formItems );
        ?>
    </div>
</form>
