<?php
$input = $this->input;
$site = $this->site;
$streamId = $input->streamId ? $input->streamId : null;
$stream = isset( $streamId ) ? $site->getStream( $streamId ) : null;
$featuredType = $input->featuredType ? $input->featuredType : 'maverick-stream';
$formatFormBootstrap = $this->formatFormBootstrap2();

$activeOnly = false;
$featuredChallenges = $site->getFeaturedChallenges( $featuredType, $activeOnly );

$hiddenFields = array(
    $formatFormBootstrap->getHiddenSimple( 'featuredType', $featuredType ),
    $formatFormBootstrap->getHiddenSimple( 'streamId', $streamId ),
);

// set the table data
$columns = array( 
    'challengeIdWithHiddenInput', 
    'challengeStatus', 
    'challengeMainImage', 
    'challengeTitle', 
    'challengeUserUsername', 
    'challengeStartTime', 
    'challengeEndTime', 
    'tableRowDelete' 
);

$columnInfo = $this->getTableInfo()->getColumnInfo( $columns );

$tableInitVars = array(
    'columns' => $columns,
    'columnInfo' => $columnInfo,
    'rowIdPrefix' => 'challenge',
    'dontUseGroups' => true,
    'tableAttributes' => array( 'class' => 'table table-striped table-bordered' ),
);

$tableDataInput = array();

$allowDuplicates = true;
$tableData = $this->getTableData( $featuredChallenges, $columns, $tableDataInput, $allowDuplicates );

$tableInitVars['rows'] = array_keys( $tableData );

$table = $this->table( $tableData, $tableInitVars );

// Stream Settings Form
$streamSettingsForm = isset( $stream ) ? $formatFormBootstrap->getStreamSettingsForm( $stream ) : false;
$streamRotationForm = isset( $stream ) ? $formatFormBootstrap->getStreamRotationForm( $stream ) : false;
$streamTableStyles =  isset( $stream ) ? $formatFormBootstrap->getStreamTableStyles( $stream ) : false;

?>


<h1 class="page-header">Edit Challenge Stream</h1>

<?php /** Change stream dropdown */ ?>
<?php if(!$streamId) : ?>
    <div class="button-bars">
        <div class="button-bar--filter button-bar">
            <form method="get" action="<?php print $this->url( 'featuredChallengesEdit' ) ?>">
                <div class="filter">
                    <?php
                    $formItems = array();
                    $formItems[] = $formatFormBootstrap->getFeaturedType( $featuredType, null, 'challenge' );
                    print $formatFormBootstrap->getList( $formItems );
                    ?>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>

<form method="get" action="<?php print $this->url( 'featuredChallengesEditConfirm' ); ?>">
    <?php /** Save button */ ?>
    <div style='display: block; float: right;'>
        <?php
        $formItems = array();
        $formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => '<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp; Save Stream', 'style' => 'btn btn-success' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );
        print $formatFormBootstrap->getList( $formItems );
        ?>
    </div>

    <?php /** Hidden Fields */ ?>
    <?php foreach($hiddenFields as $hiddenField) { print $hiddenField; } ?>

    <?php /** Stream Settings Form */ ?>
    <?php print $streamSettingsForm; ?>
    <?php print $streamRotationForm; ?>
    <?php print $streamTableStyles; ?>

    <div class="bd">
        <h3>Challenges</h3>
        <p>Search for Challenge to add and remove from the stream</p>
        <?php
        $formItems = array();
        $formItems[] = $formatFormBootstrap->getChallengeAutocomplete( null, null, '', "insert", "Search by Challenge Title, Catalyst, or Challenge ID" );
        print $formatFormBootstrap->getList( $formItems );
        ?>

        <?php /** Challenges Fields */ ?>
        <div class="table-responsive table-display-limit table-draggable">
            <?php print $table ?>
        </div>

        <?php
        $formItems = array();
        $formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => 'Submit', 'style' => 'btn btn-primary' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );
        print $formatFormBootstrap->getList( $formItems );
        ?>
    </div>
</form>
