<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Be Maverick Admin Tools</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <?php
          $this->isNavBar = true;
          print $this->render( 'nav.phtml' );
          $this->isNavBar = false;
        ?>
    </div>
  </div>
</nav>
