<?php
$input = $this->input;
$site = $this->site;
$formatFormBootstrap = $this->formatFormBootstrap2();

$userStatus = $input->userStatus;
$count = $input->count ? $input->count : 20;
$offset = $input->offset ? $input->offset : 1;
$sort = $input->sort ? $input->sort : 'id';
$sortOrder = $input->sortOrder ? $input->sortOrder : 'desc';

$filterBy = array(
    'userType' => BeMaverick_User::USER_TYPE_PARENT,
    'userStatus' => $userStatus,
);

$sortBy = array(
    'sort' => $sort,
    'sortOrder' => $sortOrder,
);

$users = $site->getUsers( $filterBy, $sortBy, $count, $offset-1 );
$userCount = $site->getUserCount( $filterBy );

// set the table data
$columns = array( 'userId', 'userStatus', 'userUsername', 'userEmailAddress', 'kidAction' );

$columnInfo = $this->getTableInfo()->getColumnInfo( $columns );

// we want the next click to be reverse sort order
$sortParams = array(
    'userStatus' => $userStatus,
    'sort' => '_sort_',
    'sortOrder' => $sortOrder == 'desc' ? 'asc' : 'desc',
);

$tableInitVars = array(
    'columns' => $columns,
    'columnInfo' => $columnInfo,
    'rowIdPrefix' => 'user',
    'dontUseGroups' => true,
    'sort' => array(
        'url' => $this->url( 'users', $sortParams ),
        'column' => 'user',
        'value' => $sort,
        'isDynamic' => true,
    ),
    'tableAttributes' => array( 'class' => 'table table-striped table-bordered' ),
);

$tableDataInput = array();

$tableData = $this->getTableData( $users, $columns, $tableDataInput );

$tableInitVars['rows'] = array_keys( $tableData );

$table = $this->table( $tableData, $tableInitVars );

// pagination params
$paginationParams = array(
    'userStatus' => $userStatus,
    'sort' => $sort,
    'sortOrder' => $sortOrder,
);

$paginationVars = array(
    'offset' => $offset,
    'urlIndex' => 'parents',
    'totalItems' => $userCount,
    'perPage' => $count,
    'itemType' => 'Parents',
    'displayPrefix' => 'Displaying',
    'of' => 'of',
    'paginationParams' => $paginationParams,
    'hideIfEmpty' => true,
    'alwaysShowPrevNext' => true,
    'labels' => array( '&laquo; Prev', 'Next &raquo;'),
    'showItemCounts' => true,
    'showPaginationIfOnePage' => false,
    'listAttributes' => array(
       'class' => 'pagination'
    ),
    'containerAttributes' => array(
        'class' => 'pagination-wrap'
    )
);

$formItems = array();
$formItems[] = $formatFormBootstrap->getUserStatus( $userStatus, null );
$formItems[] = $formatFormBootstrap->getButton( array( 'text' => 'Filter', 'style' => 'default' ) );
?>

<div class="page-header">
    <h1 class="page-header-title">Parents</h1>
    <div class="actions-wrap">
        <a href='<?php print $this->url( 'parentAdd' ); ?>' class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add New Parent
        </a>
    </div>
</div>


<div class="button-bars">
    <div class="button-bar--filter button-bar">
        <form method="get" action="<?php print $this->url( 'parents' ); ?>">
            <div class="filter">
                <?php print $formatFormBootstrap->getList( $formItems ); ?>
            </div>
        </form>
    </div>
</div>

<div class="table-responsive">
    <?php print $table; ?>
</div>

<div class="pagination-bar">
    <?php print $this->searchPagination( $paginationVars ); ?>
</div>

