<?php
$input = $this->input;
$site = $this->site;
$systemConfig = $this->systemConfig;
$formatFormBootstrap = $this->formatFormBootstrap2();

$maxProfileCoverPresetImages = $systemConfig->getSetting( 'SYSTEM_ADMIN_MAX_PROFILE_COVER_PRESET_IMAGES' );
?>

<h1 class="page-header">Edit Profile Cover Preset Images</h1>

<p>Profile Cover Images should be at a minimum of 1200x450.</p>

<form method="post" action="<?php print $this->url( 'profileCoverPresetImagesEditConfirm' ); ?>" enctype="multipart/form-data">
    <div class="bd">
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered tableType-response noGroups">
            <thead>
            <tr class="last">
                <th>Preset ID</th>
                <th>Image</th>
                <th>File</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $labelSettings = array(
                'text' => '',
            );

            $options = array(
                'returnType' => 'title',
            );

            for ( $i = 1; $i <= $maxProfileCoverPresetImages; $i++ ) {

                $imageInputSettings = array(
                    'name' => "image-$i",
                );

                $currentImageHtml = '';
                $currentImage = $site->getProfileCoverPresetImage( $i );

                if ( $currentImage ) {
                    $currentImageHtml = '<img src="' . $currentImage->getUrl( 200, 200 ) . '">';
                }

                print '<tr>';
                print '<td>' . $i . '</td>';
                print '<td>' . $currentImageHtml . '</td>';
                print '<td>' . $formatFormBootstrap->getFileUpload( $imageInputSettings, $labelSettings, $options ) . '</td>';
                print '</tr>';
            }
            ?>
            </tbody>
        </table>
        <?php
        $formItems = array();
        $formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => 'Submit', 'style' => 'btn btn-primary' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );
        print $formatFormBootstrap->getList( $formItems );
        ?>
    </div>
</form>
