<?php
$input = $this->input;
$site = $this->site;
$response = $this->response;
$formatFormBootstrap = $this->formatFormBootstrap2();

$responseType = $response->getResponseType();
$postType = $response->getPostType();

if ( $responseType == BeMaverick_Response::RESPONSE_TYPE_VIDEO ) {
    $video = $response->getVideo();
    $fileHtml = $video ? '<br/><a href="' . $video->getVideoUrl() . '">' . $video->getVideoUrl() . '</a>' : '';
} else if ( $responseType == BeMaverick_Response::RESPONSE_TYPE_IMAGE ) {
    $image = $response->getImage();
    $fileHtml = $image ? '<br/><a href="' . $image->getUrl() . '">' . $image->getUrl() . '</a>' : '';
}

$coverImageUrl = $response->getCoverImageUrl( 60, 108 );
$coverImageHtml = $coverImageUrl ? '<br/><img class="image" src="'.$coverImageUrl.'" width="60" height="108">' : '';

$challenge = $response->getChallenge();
$challengeId = (!empty($challenge)) ? $challenge->getId() : null;

$formItems = array();
$formItems[] = $formatFormBootstrap->getResponseStatus( $input->responseStatus, $response->getStatus() );
$formItems[] = $formatFormBootstrap->getHideFromStreams( $input->hideFromStreams, $response->isHideFromStreams() ? 1 : 0 );
$formItems[] = $formatFormBootstrap->getPostType( $input->responseType, $postType );
$formItems[] = $formatFormBootstrap->getResponseType( $input->responseType, $response->getResponseType() );
$formItems[] = $formatFormBootstrap->getUsername( $input->username, $response->getUser()->getUsername() );
$formItems[] = $formatFormBootstrap->getChallengeId( $input->challengeId, $challengeId, "medium" );
$formItems[] = $formatFormBootstrap->getTagNames( $input->tagNames, join( ', ', $response->getTagNames() ) );
$formItems[] = $formatFormBootstrap->getDescription( $input->description, $response->getDescription() );
$formItems[] = $formatFormBootstrap->getHashtagsValue( $response->getHashtags() );
$formItems[] = $formatFormBootstrap->getNameValueSimple( $response->isPublic() ? "yes" : "no", "Public" );

$inputSettings = array(
    'name' => "file",
);

$labelSettings = array(
    'text' => 'File Upload',
);


$formItems['file'] = $formatFormBootstrap->getFileUpload( $inputSettings, $labelSettings );
$formItems['file']['postTitleContent'] = $fileHtml;

$formItems['coverImage'] = $formatFormBootstrap->getImageFileUpload( $input->coverImage, 'coverImage', 'Cover Image' );
$formItems['coverImage']['postTitleContent'] = $coverImageHtml;

$formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => '<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp; Save', 'style' => 'btn btn-success' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );
?>

<h1 class="page-header">Edit Post</h1>

<form method="post" action="<?php print $this->url( 'responseEditConfirm' ); ?>" enctype="multipart/form-data">
    <input type="hidden" name="responseId" value="<?php print $response->getId() ?>">
    <div class="bd">
        <?php print $formatFormBootstrap->getList( $formItems ); ?>
    </div>
</form>
