<?php
$input = $this->input;
$site = $this->site;
$formatFormBootstrap = $this->formatFormBootstrap2();

$streamStatus = $input->contentStatus ? $input->contentStatus : null;
$query = $input->getUnescaped( 'query' );
$count = $input->count ? $input->count : 99;
$offset = $input->offset ? $input->offset : 1;
$sort = $input->sort ? $input->sort : 'id';
$sortOrder = $input->sortOrder ? $input->sortOrder : 'desc';

$filterStatus = !is_null($streamStatus) ? $streamStatus : array ('active', 'inactive', 'draft');
$filterBy = array(
    'status' => $filterStatus,
    'query' => $query,
);

$sortBy = array(
    'sort' => $sort,
    'sortOrder' => $sortOrder,
);

$streams = $site->getStreams( $filterBy, $sortBy, $count, $offset-1 );
$streamCount = $site->getStreamCount( $filterBy );

// set the table data
$columns = array(
    // 'upDown',
    'streamIdWithHiddenInput',
    'streamStatus',
    'streamLabel',
    'streamType',
    'streamModelType',
    // 'streamUpdated',
    'streamAction'
);

$columnInfo = $this->getTableInfo()->getColumnInfo( $columns );

// we want the next click to be reverse sort order
$sortParams = array(
    'streamStatus' => $streamStatus,
    'query' => $query,
    'sort' => '_sort_',
    'sortOrder' => $sortOrder == 'desc' ? 'asc' : 'desc',
);

$tableInitVars = array(
    'columns' => $columns,
    'columnInfo' => $columnInfo,
    'rowIdPrefix' => 'stream',
    'dontUseGroups' => true,
    'sort' => array(
        'url' => $this->url( 'streams', $sortParams ),
        'column' => 'stream',
        'value' => $sort,
        'isDynamic' => true,
    ),
    'tableAttributes' => array( 'class' => 'table table-striped table-bordered' ),
);

$tableDataInput = array();

$tableData = $this->getTableData( $streams, $columns, $tableDataInput );

$tableInitVars['rows'] = array_keys( $tableData );

$table = $this->table( $tableData, $tableInitVars );

// pagination params
$paginationParams = array(
    'status' => $streamStatus,
    'query' => $query,
    'sort' => $sort,
    'sortOrder' => $sortOrder,
);

$paginationVars = array(
    'offset' => $offset,
    'urlIndex' => 'streams',
    'totalItems' => $streamCount,
    'perPage' => $count,
    'itemType' => 'Streams',
    'displayPrefix' => 'Displaying',
    'of' => 'of',
    'paginationParams' => $paginationParams,
    'hideIfEmpty' => true,
    'alwaysShowPrevNext' => true,
    'labels' => array( '&laquo; Prev', 'Next &raquo;'),
    'showItemCounts' => true,
    'showPaginationIfOnePage' => false,
    'listAttributes' => array(
       'class' => 'pagination'
    ),
    'containerAttributes' => array(
        'class' => 'pagination-wrap'
    )
);

$formItems = array();
$formItems[] = $formatFormBootstrap->getContentStatus( $streamStatus, null );
$formItems[] = $formatFormBootstrap->getQuery( $query, null, 'Label' );
$formItems[] = $formatFormBootstrap->getButton( array( 'text' => 'Filter', 'style' => 'default' ) );
?>


<div class="page-header">
    <h1 class="page-header-title">Streams</h1>
    <div class="actions-wrap">
        <!-- <a href='<?php print $this->url( 'streamAdd' ); ?>' class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add New Stream
        </a> -->
    </div>
</div>

<?php /** Filter Form */ ?>
<div class="button-bars">
    <div class="button-bar--filter button-bar">
        <form method="get" action="<?php print $this->url( 'streams' ); ?>">
            <div class="filter">
                <?php print $formatFormBootstrap->getList( $formItems ); ?>
            </div>
        </form>
    </div>
</div>

<form method="get" action="<?php print $this->url( 'streamsEditConfirm' ); ?>" >

    <div class="table-responsive table-draggable">
        <?php print $table; ?>
    </div>

    <?php
    $formItems = array();
    $formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => 'Save Order', 'style' => 'btn btn-success' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );
    print $formatFormBootstrap->getList( $formItems );
    ?>
</form>

<div class="pagination-bar">
    <?php print $this->searchPagination( $paginationVars ); ?>
</div>

<?php /** Add New Form */ 

$formItems = array();
$formItems[] = $formatFormBootstrap->getLabel( 'A New Stream', null );
$formItems[] = $formatFormBootstrap->getStreamType( '', null );
$formItems[] = $formatFormBootstrap->getButton( array( 'text' => '<span class="glyphicon glyphicon-plus"></span>&nbsp; Add New Stream', 'style' => 'default' ) );

?>

<h3>Add a New Stream</h3>
<div class="button-bars">
    <div class="button-bar--filter button-bar">
        <form method="get" action="<?php print $this->url( 'streamsAddStreamConfirm' ); ?>">
            <div class="filter">
                <?php print $formatFormBootstrap->getList( $formItems ); ?>
            </div>
        </form>
    </div>
</div>