<?php
$input = $this->input;
$site = $this->site;
$systemConfig = $this->systemConfig;
$user = $this->user;
$userType = $user->getUserType();
$formatFormBootstrap = $this->formatFormBootstrap2();

// get profile image
$profileImage = $user->getProfileImage();
$profileImageHtml = '';


if ( $profileImage ) {
    $removeImageUrl = $this->url( 'kidRemoveImageConfirm', array( 'userId' => $user->getId() ) );

    $profileImageHtml = '<div style="margin-bottom: 20px; display: flex; align-items: flex-end;">
                   <img src="' . $profileImage->getUrl( 300, 300 ) . '" width="300" height="300">
                   <a href="'.$removeImageUrl.'" class="btn btn-danger" style="margin-left: 20px;">Remove Profile Image</a>
               </div>';
}

$loginProvidersText = (count($user->getLoginProviders()) > 0) ? implode(', ', $user->getLoginProviders()) : "<em>none</em>";

$formItems = array();
$formItems[] = $formatFormBootstrap->getUsername( $input->username, $user->getUsername() );
$formItems[] = $formatFormBootstrap->getUserType( $input->userType, $user->getUserType() );
$formItems[] = $formatFormBootstrap->getUserStatus( $input->userStatus, $user->getStatus() );
$formItems[] = $formatFormBootstrap->getUserRevokedReason( $input->userRevokedReason, $user->getRevokedReason() );
$formItems[] = $formatFormBootstrap->getIsVerified( $input->isVerified, $user->isVerified() );
$formItems[] = $formatFormBootstrap->getFirstName( $input->getUnescaped( 'firstName' ), $user->getFirstName() );
$formItems[] = $formatFormBootstrap->getLastName( $input->getUnescaped( 'lastName' ), $user->getLastName() );
$formItems[] = $formatFormBootstrap->getIsEmailVerified( $user->isEmailVerified() );
$formItems[] = $formatFormBootstrap->getBirthdate( $input->birthdate, $user->getBirthdate() );
$formItems[] = $formatFormBootstrap->getEmailAddress( $input->emailAddress, $user->getEmailAddress() );
$formItems[] = $formatFormBootstrap->getParentEmailAddress( $input->parentEmailAddress, $user->getParentEmailAddress() );
$formItems[] = $formatFormBootstrap->getBio( $input->getUnescaped( 'bio' ), $user->getBio() );
$formItems[] = $formatFormBootstrap->getHashtagsValue( $user->getHashtags() );
$formItems[] = $formatFormBootstrap->getNameValueSimple( $user->getPhoneNumber() ?? "<em>none</em>", 'Phone Number');
$formItems[] = $formatFormBootstrap->getNameValueSimple( $loginProvidersText, 'Login Providers');
$formItems[] = $formatFormBootstrap->getButtons( array( array( 'text' => 'Submit', 'style' => 'btn btn-primary' ) ), $formatFormBootstrap->getDefaultButtonsOptions() );

$deleteKidUrl = $this->url( 'userDeleteConfirm', array( 'userId' => $user->getId() ) );
?>

<h1 class="page-header">Edit Maverick</h1>

<?php print $profileImageHtml ?>

<form method="post" action="<?php print $this->url( 'kidEditConfirm' ); ?>">
    <input type="hidden" name="userId" value="<?php print $user->getId() ?>">
    <div class="bd">
        <?php print $formatFormBootstrap->getList( $formItems ); ?>
    </div>
</form>

<?php if ( $systemConfig->getEnvironment() != 'production' ) { ?>
<br/><br/>

<a href="<?php print $deleteKidUrl ?>" class="btn btn-danger">Delete Maverick</a>
<?php } ?>


