<?php
// globals
$input = $this->input;
$translator = $this->translator;
$user = $this->user;

// formatters
$formatModule = $this->formatModule();
$formatUtil = $this->formatUtil();
$formatFormBootstrap = $this->formatFormBootstrap2();

// module stuff
$moduleClassPrefix = 'auth-login';
$typeClassPrefix = 'login-module';

$classPrefixes = array(
    $moduleClassPrefix,
    $typeClassPrefix
);

$classNames = array();

// header content
$headerContent = $formatModule->getBasicModuleHeader(
    array(
//        'returnLinkUrl' => $this->url( 'authLogin' ),
        'title' => $translator->_( 'Forgot Your Password?' )
    )
);

// body content
$bodyContent = array();

$forgotUsernameUrl = $this->url( 'authUsernameForgot' );
$forgotPasswordConfirmUrl = $this->url( 'authPasswordForgotConfirm' );

$formItems = array();

$formItems['emailAddress'] = $formatFormBootstrap->getEmailAddress($input->emailAddress, '', array('attributes' => array('placeholder' => 'Enter your email address') ), array('text' => '') );

$buttons = array(
    array(
        'text' => $translator->_( 'Submit' ),
        'type' => 'submit',
        'style' => 'primary-gradient',
    ),
);

$options = $formatUtil->getSetting( 'button-options' );

/*
$options['preContent'] = '
    <div class="additional-actions">
        <a href="'.$forgotUsernameUrl.'" class="forgot">'.$translator->_( 'Forgot Username?' ).'</a>
    </div>
';
*/

$formItems['buttons'] = $formatFormBootstrap->getButtons( $buttons, $options );

$unAssociatedErrors = $this->render( 'unAssociatedErrors.phtml' );


$bodyContent [] = '
    <p class="instructions">
        '.$translator->_( "We'll email you a link to reset your password." ).'
    </p>
    '.$unAssociatedErrors.'
    <form action="'.$forgotPasswordConfirmUrl.'" method="POST">
        '.$formatFormBootstrap->getList( $formItems ).'
    </form>
';

// print module
print $formatModule->getBasicLoginModule(
    array(
        'headerContent' => join( '', $headerContent ),
        'bodyContent' => join( '', $bodyContent ),
        'classPrefixes' => $classPrefixes,
        'attributes' => array(
            'class' => join( ' ', $classNames )
        )
    )
);
?>


