<?php
// globals
$translator = $this->translator;
$input = $this->input;

// formatters
$formatModule = $this->formatModule();
$formatUtil = $this->formatUtil();
$formatFormBootstrap = $this->formatFormBootstrap2();

// module stuff
$moduleClassPrefix = 'auth-login';
$typeClassPrefix = 'login-module';

$classPrefixes = array(
    $moduleClassPrefix,
    $typeClassPrefix
);

$classNames = array();

// header content
$headerContent = $formatModule->getBasicModuleHeader(
    array(
        'title' => $translator->_( 'Reset Password' )
    )
);

// body content
$bodyContent = array();

$passwordResetConfirmUrl = $this->url( 'authPasswordResetConfirm' );
$unAssociatedErrors = $this->render( 'unAssociatedErrors.phtml' );

$formItems = array();
$formItems['password'] = $formatFormBootstrap->getPassword( $input->getUnescaped( 'password' ), '', array('attributes' => array('placeholder' => 'New password') ), array('text' => '') );

$buttons = array(
    array(
        'text' => $translator->_( 'Submit' ),
        'type' => 'submit',
        'style' => 'primary-gradient',
    ),
);
$options = $formatUtil->getSetting( 'button-options' );

$formItems['buttons'] = $formatFormBootstrap->getButtons( $buttons, $options );

$bodyContent[] = '
    '.$unAssociatedErrors.'
    <form action="'.$passwordResetConfirmUrl.'" method="POST">
        '.$formatFormBootstrap->getHiddenSimple( 'code', $input->code ).'
        '.$formatFormBootstrap->getList( $formItems ).'
    </form>
';

// print module
print $formatModule->getBasicLoginModule(
    array(
        'headerContent' => join( '', $headerContent ),
        'bodyContent' => join( '', $bodyContent ),
        'classPrefixes' => $classPrefixes,
        'attributes' => array(
            'class' => join( ' ', $classNames )
        )
    )
);
?>
