<?php
// globals
$translator = $this->translator;

// formatters
$formatModule = $this->formatModule();
$formatUtil = $this->formatUtil();

// module stuff
$moduleClassPrefix = 'auth-login';
$typeClassPrefix = 'login-module';

$classPrefixes = array(
    $moduleClassPrefix,
    $typeClassPrefix
);

$classNames = array();

//// header content
//$headerContent = $formatModule->getBasicModuleHeader(
//    array(
//        'title' => $translator->_( 'Reset Password' )
//    )
//);

// body content
$bodyContent = array();
$bodyContent[] =
    '<div class="confirm-message">
        <p>
            '.$translator->_( 'Your password has been reset.' ).'
        </p>
    </div>
';

// print module
print $formatModule->getBasicLoginModule(
    array(
        'headerContent' => '',
        'bodyContent' => join( '', $bodyContent ),
        'classPrefixes' => $classPrefixes,
        'attributes' => array(
            'class' => join( ' ', $classNames )
        )
    )
);
?>
