<?php
// globals
$translator = $this->translator;
$input = $this->input;

// formatters
$formatModule = $this->formatModule();
$formatUtil = $this->formatUtil();

// module stuff
$moduleClassPrefix = 'auth-login';
$typeClassPrefix = 'login-module';

$classPrefixes = array(
    $moduleClassPrefix,
    $typeClassPrefix
);

$classNames = array();

//// header content
//$headerContent = $formatModule->getBasicModuleHeader(
//    array(
//        'title' => $translator->_( 'Forgot your password?' )
//    )
//);

// body content
$bodyContent = array();

$username = $input && $input->emailAddress ? $input->emailAddress : "TEST";

$bodyContent[] ='
    <div class="confirm-message">
        <p>
            '.$translator->_( 'A reset password link was sent to the email address associated with: ' ).'
            <br/>
            <strong>
                '.$username.'
            </strong>
        </p>
    </div>
';

// print module
print $formatModule->getBasicLoginModule(
    array(
        'headerContent' => '',
        'bodyContent' => join( '', $bodyContent ),
        'classPrefixes' => $classPrefixes,
        'attributes' => array(
            'class' => join( ' ', $classNames )
        )
    )
);
?>