<?php
print '
    <div class="home-details home-details--1">
        <div class="home-details__wrap">
            <div class="home-details__content">
                <div class="home-details__text-wrap">
                    <div class="home-details__title">
                        How does Maverick work?
                    </div>
                    <div class="home-details__text">
                        <p>
                            Mauris sit amet enim eu lectus malesuada egestas. Sed vehicula sit amet magna id ultrices. Ut tellus sapien, rutrum vitae convallis at, fermentum eget nisl. Mauris sit amet enim eu lectus malesuada egestas. Sed vehicula sit amet magna id ultrices. Ut tellus sapien, rutrum vitae convallis at, fermentum eget nisl.
                        </p>
                    </div>
                    <div class="home-details__cta">
                        <a href="#">Learn more <span class="svgicon--caret flip-horizontal"></span></a>
                    </div>
                </div>
            </div>
            <div class="home-details__image-wrap">
                <div class="proxy-img home-details__image" data-img-src="'.$this->url( 'imageStatic', array( 'imageName' => 'collage1.jpg' ) ).'"></div>
            </div>
        </div>
    </div>
    <div class="home-details home-details--2">
        <div class="home-details__wrap">
            <div class="home-details__content">
                <div class="home-details__text-wrap">
                    <div class="home-details__title">
                        Why Maverick?
                    </div>
                    <div class="home-details__text">
                        <p>
                            Mauris sit amet enim eu lectus malesuada egestas. Sed vehicula sit amet magna id ultrices. Ut tellus sapien, rutrum vitae convallis at, fermentum eget nisl. Mauris sit amet enim eu lectus malesuada egestas. Sed vehicula sit amet magna id ultrices. Ut tellus sapien, rutrum vitae convallis at, fermentum eget nisl.
                        </p>
                    </div>
                    <div class="home-details__cta">
                        <a href="#">Learn more <span class="svgicon--caret flip-horizontal"></span></a>
                    </div>
                </div>
            </div>
            <div class="home-details__image-wrap">
                <div class="proxy-img home-details__image" data-img-src="'.$this->url( 'imageStatic', array( 'imageName' => 'collage2.jpg' ) ).'"></div>
            </div>
        </div>
    </div>
';
?>