<?php
$response = $this->response;
$translator = $this->translator;
$loginUser = $this->loginUser;
$pageConfig = $this->pageConfig;

$formatModule = $this->formatModule();
$classPrefixes = array(
    'response-flag',
    'basic-popup-module'
);
$classNames = array();
$bodyContent = array();
$title = 'Error';

$isConfirm = $pageConfig->getName() == 'responseFlagConfirm' ? true : false;


if ( ! $isConfirm ) {
    $accessToken = $loginUser->getOAuthAccessToken();

    $title = 'Report Response';
    $value = 'inactive';
    $description = 'Reporting this response will flag this video for moderation by the Maverick team.';
    $cta = 'Report';
    $question = 'Are you sure you want to report this response?';

    $bodyContent[] = '
        <p>'.$translator->_( $description ).'</p>
        <p>'.$translator->_( $question ).'</p>
        <form action="'.$response->getUrl( 'responseFlagConfirm' ).'" method="post" data-request-name="responseReportConfirm">
            <input type="hidden" name="accessToken" value="'.$accessToken.'">
            <button type="submit" class="button">'.$translator->_( $cta ).'</button>
        </form>
    ';
} else {
    $title = 'Response Reported';
    $description = 'You have successfully reported this response.';
    $bodyContent[] = '
        <p>'.$translator->_( $description ).'</p>
    ';
}




print $formatModule->getModule(
    array(
        'body' => array(
            'content' => '
                <div class="'.join( ' ', $formatModule->getPrefixedClasses( 'bd-content', $classPrefixes ) ).'">
                    '.join( '', $bodyContent ).'
                </div>
            '
        ),
        'attributes' => array(
            'class' => join( ' ', $classNames )
        ),
        'classPrefixes' => $classPrefixes
    )
);
$this->AddItem( 'popupSettings', $title, 'title' );
$this->AddItem( 'popupSettings', 'basic', 'type' );
?>