<?php
// globals
$site = $this->site;
$translator = $this->translator;
$user = $this->user;
$input = $this->input;
$loginUser = $this->loginUser;

// formatters
$formatModule = $this->formatModule();
$formatUtil = $this->formatUtil();
$formatFormBootstrap2 = $this->formatFormBootstrap2();

// module stuff
$moduleClassPrefix = 'user-password-edit';
$typeClassPrefix = 'user-settings-module';

$classPrefixes = array(
    $moduleClassPrefix,
    $typeClassPrefix
);

// header content
$headerContent = array();
$headerContent[] = '
    <h1 class="'.join( ' ', $formatModule->getPrefixedClasses( 'title', $classPrefixes ) ).'">
        '.$translator->_( 'Change password' ).'
    </h1>
';


// body content
$bodyContent = array();

$formItems = array();
$formItems['currentPassword'] = $formatFormBootstrap2->getPassword(
    $input->currentPassword, '',
    array(
        'name' => 'currentPassword'
    ),
    array(
        'text' => $translator->_( "Current password" )
    )
);
$formItems['newPassword'] = $formatFormBootstrap2->getPassword(
    $input->newPassword, '',
    array(
        'name' => 'newPassword'
    ),
    array(
        'text' => $translator->_( "New password" )
    )
);
$formItems['confirmPassword'] = $formatFormBootstrap2->getPassword(
    $input->currentPassword, '',
    array(
        'name' => 'confirmPassword'
    ),
    array(
        'text' => $translator->_( "Confirm new password" )
    )
);
// button
$buttonOptions = $formatUtil->getSetting( 'button-options' );
$formItems[] = $formatFormBootstrap2->getButtons(
    array(
        array(
            'type' => 'submit',
            'text' => $translator->_( 'Save' ),
            'style' => 'primary',
        )
    ),
    $buttonOptions
);

if ( $input->confirmMessage ) {
    $bodyContent[] = '
        <div class="confirm-message fade-out trigger-transition">
            '.$translator->_( 'Your changes have been saved' ).'
        </div>
    ';
}
// body content
$bodyContent[] = $this->render( 'unAssociatedErrors.phtml' );

$formAction = $user->getUrl( 'userPasswordEditConfirm' );
$bodyContent[] = '
    <form action="'.$formAction.'" method="post">
        '.$formatFormBootstrap2->getList( $formItems ).'
        '.$formatFormBootstrap2->getHiddenSimple( 'accessToken', $loginUser->getOAuthAccessToken() ).'
    </form>
';

// print module
print $formatModule->getModule(
    array(
        'header' => array(
            'content' => '
                <div class="'.join( ' ', $formatModule->getPrefixedClasses( 'hd-content', $classPrefixes ) ).'">
                    '.join( '', $headerContent ).'
                </div>
            ',
        ),
        'body' => array(
            'content' => '
                <div class="'.join( ' ', $formatModule->getPrefixedClasses( 'bd-content', $classPrefixes ) ).'">
                    '.join( '', $bodyContent ).'
                </div>
            ',
        ),
        'classPrefixes' => $classPrefixes,
    )
);
?>