# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: npm install
  test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Lint
          command: npm run lint
  deploy-dev:
    docker:
      # - image: docker:17.05.0-ce-git
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Download .env variables
          command: npm run deploy
      - run:
          name: Deploy to AWS Lambda
          commands:
            - aws s3 sync s3://bemaverick-infrastructure-deployment/bemaverick-services/comment-service/.env/ ./.env --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test
        requires:
          - build
      - deploy-dev:
          filters:
            branches:
              only: master
          requires:
            - build
            - test
      # - deploy-prod:
      #     filters:
      #       branches:
      #         only: release
      #     requires:
      #       - build
