<?php
$site = $this->site;
$serviceDocXml = $this->serviceDocXml;

$httpHost = $this->systemConfig->getSetting( 'SYSTEM_HTTP_HOST' );
$apiVersion = $this->systemConfig->getSetting( 'SYSTEM_API_VERSION' );
?>
<div id="docsHome" class="mod docs">
    <div class="content">
        <div class="bd">

            <section>
                <h3>Name</h3>
                <p><?php print $serviceDocXml->name ?></p>
            </section>
            <section>
                <h3>Description</h3>
                <p><?php print $serviceDocXml->description ?></p>
            </section>
            <section>
                <h3>Uri</h3>
                <p><?php print '/'.$apiVersion.$serviceDocXml->uri ?></p>
            </section>
            <section>
                <h3>Method</h3>
                <p><?php print $serviceDocXml->method ?></p>
            </section>
            <section>
                <h3>Parameters</h3>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Required</th>
                        <th>Default</th>
                        <th>Format</th>
                        <th>Examples</th>
                        <th>Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach( $serviceDocXml->parameters->param as $param ) {
                        print '<tr>';
                        print '<td class="name">' . $param->name . '</td>';
                        print '<td class="required">' . $param->required . '</td>';
                        print '<td class="default">' . $param->default . '</td>';
                        print '<td class="format">' . $param->format . '</td>';
                        print '<td class="examples">' . $param->examples . '</td>';
                        print '<td class="description">' . $param->description . '</td>';
                        print '</tr>';
                    }
                    ?>
                    </tbody>
                </table>
            </section>

            <?php if ( $serviceDocXml->request_body ) { ?>
                <section>
                    <h3>Request Body</h3>
                    <pre><?php
                        print htmlentities( json_encode( json_decode( $serviceDocXml->request_body ), JSON_PRETTY_PRINT ) );
                        ?></pre>
                </section>
            <?php } ?>

            <?php if ( $serviceDocXml->response_description ) { ?>
                <section>
                    <h3>Response Description</h3>
                    <?php print $serviceDocXml->response_description ?>
                </section>
            <?php } ?>

            <?php if ( $serviceDocXml->example_request ): ?>
                <section>
                    <h3>Example Request</h3>
                    <code>
                        <a target="_request" href="<?php print 'https://' . $httpHost.'/'.$apiVersion.$serviceDocXml->example_request ?>">
                            <?php print 'https://' . $httpHost.'/'.$apiVersion.$serviceDocXml->example_request ?>
                        </a>
                    </code>
                </section>
            <?php endif; ?>

            <?php if ( $serviceDocXml->example_curl ) { ?>
                <section>
                    <h3>Example cURL Request</h3>
                    <?php
                    $accessTokenSigningSecret = $this->systemConfig->getAccessTokenSigningSecret();

                    $accessTokenManger = new Sly_OAuth_AccessTokenManager();
                    $accessTokenManger->setAccessTokenSigningSecret( $accessTokenSigningSecret );
                    $accessTokenManger->setTokenTTL( 86400 ); // 24 hours.

                    $oAuthAccessToken = $accessTokenManger->createAccessToken( 'test_key', null, null, false );

                    $curlRequest = $serviceDocXml->example_curl;
                    $curlRequest = preg_replace('/<host>/i', 'https://'.$httpHost, $curlRequest );
                    $curlRequest = preg_replace('/<accessToken>/i', $oAuthAccessToken['access_token'], $curlRequest );

                    print '<pre>' . htmlentities( $curlRequest ) . '</pre>';
                    ?>
                </section>
            <?php } ?>

            <?php if ( $serviceDocXml->example_json_response ) { ?>
                <section>
                    <h3>Example JSON Response</h3>
                    <pre><?php
                        $jsonResponse = preg_replace( '/<host>/i', $httpHost, $serviceDocXml->example_json_response );
                        print htmlentities( json_encode( json_decode( $jsonResponse ), JSON_PRETTY_PRINT ) );
                        ?></pre>
                </section>
            <?php } ?>

            <?php if ( $serviceDocXml->example_xml_response ) { ?>
                <section>
                    <h3>Example XML Response</h3>
                    <pre><?php
                        print htmlentities( $serviceDocXml->example_xml_response );
                        ?></pre>
                </section>
            <?php } ?>

        </div>
    </div>
</div>
