<?php

/**
 * @see Zend_Filter_Interface
 */
require_once 'Zend/Filter/Interface.php';


/**
 * @category   Sly
 * @package    Sly_Filter
 */
class Sly_Filter_ProfanityMinimal implements Zend_Filter_Interface
{

    private $profanity = array(
        '5h1t',
        '5hit',
        'a_s_s',
        'a2m',
        'arsehole',
        'assfucker',
        'ass-fucker',
        'assfukka',
        'asshole',
        'assholes',
        'assmucus',
        'assmunch',
        'asswhole',
        'b!tch',
        'b00bs',
        'b17ch',
        'b1tch',
        'bangbros',
        'beef curtain',
        'bi+ch',
        'bitch',
        'bitch tit',
        'bitcher',
        'bitchers',
        'bitches',
        'bitchin',
        'bitching',
        'blow job',
        'blow me',
        'blowjob',
        'blowjobs',
        'bust a load',
        'butt fuck',
        'butthole',
        'buttmunch',
        'buttplug',
        'c0ck',
        'c0cksucker',
        'carpet muncher',
        'carpetmuncher',
        'cawk',
        'chink',
        'choade',
        'cl1t',
        'clit',
        'clit licker',
        'clits',
        'clitty litter',
        'clusterfuck',
        'cnut',
        'cock',
        'cockface',
        'cockhead',
        'cockmunch',
        'cockmuncher',
        'cocks',
        'cocksuck',
        'cocksucked',
        'cocksucker',
        'cock-sucker',
        'cocksucking',
        'cocksucks',
        'cocksuka',
        'cocksukka',
        'cok',
        'cokmuncher',
        'coksucka',
        'coon',
        'cumdump',
        'cummer',
        'cumming',
        'cumshot',
        'cunt',
        'cuntbag',
        'cuntlick',
        'cuntlicker',
        'cuntlicking',
        'cunts',
        'cuntsicle',
        'cunt-struck',
        'cyberfuc',
        'cyberfuck',
        'cyberfucked',
        'cyberfucker',
        'cyberfuckers',
        'cyberfucking',
        'dickhead',
        'dirty Sanchez',
        'dog-fucker',
        'doggiestyle',
        'doggin',
        'donkeyribber',
        'doosh',
        'duche',
        'dyke',
        'f u c k',
        'f u c k e r',
        'f_u_c_k',
        'f4nny',
        'fag',
        'fagging',
        'faggitt',
        'faggot',
        'faggs',
        'fagot',
        'fagots',
        'fags',
        'fannyflaps',
        'fannyfucker',
        'fatass',
        'feck',
        'fecker',
        'fellate',
        'fellatio',
        'fistfuck',
        'fistfucked',
        'fistfucker',
        'fistfuckers',
        'fistfucking',
        'fistfuckings',
        'fistfucks',
        'fook',
        'fooker',
        'fuck',
        'fucka',
        'fuck-ass',
        'fuck-bitch',
        'fucked',
        'fucker',
        'fuckers',
        'fuckhead',
        'fuckheads',
        'fuckin',
        'fucking',
        'fuckings',
        'fuckingshitmotherfucker',
        'fuckme',
        'fuckmeat',
        'fucks',
        'fucktoy',
        'fuckwhit',
        'fuckwit',
        'fudgepacker',
        'fuk',
        'fuker',
        'fukker',
        'fukkin',
        'fuks',
        'fukwhit',
        'fukwit',
        'fux',
        'fux0r',
        'goatse',
        'hardcoresex',
        'heshe',
        'hoar',
        'hoer',
        'homo',
        'jackoff',
        'jack-off',
        'jap',
        'jism',
        'jiz',
        'jizm',
        'jizz',
        'kawk',
        'knobhead',
        'knobjocky',
        'knobjokey',
        'kock',
        'kum',
        'kummer',
        'kumming',
        'kums',
        'kwif',
        'mafugly',
        'mothafuck',
        'mothafucka',
        'mothafuckas',
        'mothafuckaz',
        'mothafucked',
        'mothafucker',
        'mothafuckers',
        'mothafuckin',
        'mothafucking',
        'mothafuckings',
        'mothafucks',
        'motherfuck',
        'motherfucked',
        'motherfucker',
        'motherfuckers',
        'motherfuckin',
        'motherfucking',
        'motherfuckings',
        'motherfuckka',
        'motherfucks',
        'n1gga',
        'n1gger',
        'nigg3r',
        'nigg4h',
        'nigga',
        'niggah',
        'niggas',
        'niggaz',
        'nigger',
        'niggers',
        'penisfucker',
        'phuck',
        'phuk',
        'phuked',
        'phuking',
        'phukked',
        'phukking',
        'phuks',
        'phuq',
        'prick',
        'pricks',
        'pusse',
        'pussies',
        'pussy',
        'pussys',
        'queer',
        'retard',
        's hit',
        's_h_i_t',
        'sh!+',
        'sh!t',
        'sh1t',
        'shi+',
        'shit',
        'shitdick',
        'shite',
        'shited',
        'shitey',
        'shitfuck',
        'shitfull',
        'shithead',
        'shiting',
        'shitings',
        'shits',
        'shitted',
        'shitter',
        'shitters',
        'shitting',
        'shittings',
        'shitty',
        'smegma',
        'son-of-a-bitch',
        't1tt1e5',
        't1tties',
        'titfuck',
        'tits',
        'tittiefucker',
        'titties',
        'tittyfuck',
        'tittywank',
        'titwank',
        'tw4t',
        'twat',
        'twathead',
        'twatty',
        'twunt',
        'twunter',

    );
    
    /**
     * Defined by Zend_Filter_Interface
     *
     * Returns the string $value, stripping the chars
     *
     * @param  string $value
     * @return string
     */
    public function filter($value)
    {
        
        foreach( $this->profanity as $word ) {
            $value = preg_replace( "/\b$word\b/", str_repeat( '*', strlen($word) ), $value );
        }
        
        return $value;    
    }

}

?>
