#!/bin/bash

export SLYTRUNK_ENV='slytrunk_test'
export PROJECT_ROOT=/home/$USER/dev/bemaverick-web

# Configure for container creation
cd $PROJECT_ROOT/docker/bootstrap/
./bootstrap

# Start local Redis
service redis-server start

# Start local Apache
service apache2 start

# Start local LESS Server
nohup node /home/$USER/dev/less.js-server/lessServer.js > /dev/null &

# Run Migrations
cd $PROJECT_ROOT/database/config
cd $PROJECT_ROOT
ln -sf $PROJECT_ROOT/vendor/robmorgan/phinx/bin/phinx /bin/phinx
phinx migrate -c database/bemaverick/phinx.php
echo ""

# Run Tests
cd $PROJECT_ROOT
ln -sf $PROJECT_ROOT/vendor/phpunit/phpunit/phpunit /bin/phpunit
phpunit -c tests/phpunit.xml
cat /var/log/apache2/error.log
